version: "3.8"
services:

  fibonacci:
    container_name: fibonacci
    build:
      dockerfile: /Fibonacci/Dockerfile

  rabbitmq:
    container_name: rabbitmq
    build:
      dockerfile: /RabbitMQServer/Dockerfile
      
  webapi:
    container_name: webapi
    build:
      dockerfile: /WebApi/Dockerfile
    depends_on:
      - rabbitmq
      - fibonacci

  httpclient:
    container_name: httpclient
    build:
      dockerfile: /HttpClient/Dockerfile
    restart: on-failure
    entrypoint: ["dotnet", "run"]
    depends_on:
      - rabbitmq
      - webapi
      - fibonacci
    links: 
        - rabbit

networks:
  fibonacci_network:
    driver: bridge