# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  fibonacci:
    image: fibonacci
    build:
      context: .
      dockerfile: Fibonacci/Dockerfile
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    depends_on:
      - fibonacci
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - 5278:8080
    depends_on:
      - fibonacci
      - rabbitmq
    command: sh -c './wait-for localhost:5672 -t 20'
  httpclient:
    image: httpclient
    build:
      context: .
      dockerfile: HttpClient/Dockerfile
    depends_on:
      - fibonacci
      - rabbitmq
      - webapi